on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Haskell cabal-cache
        uses: haskell-works/cabal-cache-action@master
      - run: runhaskell code.hs
